### ISSUE TITLE
internal links are tagged as external

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/bluexp-operational-resiliency#7]
### Page URL

https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/quick-start.html

### Page title

Quick start for BlueXP operational resiliency

### Summary

Internal links are tagged as external.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Changed links in Quick Start. 
https://docs.netapp.com/us-en/bluexp-operational-resiliency/get-started/quick-start.html
